import os
import sys
import glob
import numpy as np
from skimage import io
#from sklearn import datasets
from sklearn import utils
import cv2
 
IMAGE_SIZE = 40
#COLOR_BYTE = 3
COLOR_BYTE = 1
CATEGORY_NUM = 6
threshhold = 80
 
## ラベル名(0～)を付けたディレクトリに分類されたイメージファイルを読み込む
## 入力パスはラベル名の上位のディレクトリ
def load_handimage_bin(path):
 
    # ファイル一覧を取得
    files = glob.glob(os.path.join(path, '*/*.png'))
 
    # イメージとラベル領域を確保
    #images = np.ndarray((len(files), IMAGE_SIZE, IMAGE_SIZE,
    #                      COLOR_BYTE), dtype = np.uint8)
    images = np.ndarray((len(files), IMAGE_SIZE, IMAGE_SIZE)
                           , dtype = np.uint8)
 
    labels = np.ndarray(len(files), dtype=np.int)
 
    # イメージとラベルを読み込み
    for idx, file in enumerate(files):
        # イメージ読み込み
        image = io.imread(file)
        #image = cv2.GaussianBlur(image, (3,3), 0) # 必要に応じて、ぼかしでノイズ対策
        retval,image = cv2.threshold(image, threshhold, 255, cv2.THRESH_BINARY)
        images[idx] = image[:,:,0] | image[:,:,1] | image[:,:,2]
 
        # ディレクトリ名よりラベルを取得
        label = os.path.split(os.path.dirname(file))[-1]
        labels[idx] = int(label)
 
    # scikit-learn の他のデータセットの形式に合わせる
    flat_data = images.reshape((-1, IMAGE_SIZE * IMAGE_SIZE * COLOR_BYTE))
    images = flat_data.view()
    #return datasets.base.Bunch(data=images,
    return utils.Bunch(data=images,
                 target=labels.astype(np.int),
                 target_names=np.arange(CATEGORY_NUM),
                 images=images,
                 DESCR=None)
 
if __name__ == '__main__':
    import matplotlib.pyplot as plt

    d = load_handimage_bin("./data/m01")
    plt.figure(figsize=(8, 8))
    # 画像を 2 行 3 列に表示
    k = 0
    for i in range(6):
        for j in range(4):
            img = d.images[d.target==i][j]
            k += 1
            plt.subplot(6,4, k)
            plt.axis('off')
            plt.imshow(img.reshape(40,40), cmap="gray", interpolation='nearest')
            plt.title(i)
    plt.tight_layout()
    plt.show()

In [ ]:
import os
import sys
import glob
import numpy as np
from skimage import io
#from sklearn import datasets
from sklearn import utils
import cv2
 
IMAGE_SIZE = 40
#COLOR_BYTE = 3
COLOR_BYTE = 1
CATEGORY_NUM = 6
threshhold = 80
 
## ラベル名(0～)を付けたディレクトリに分類されたイメージファイルを読み込む
## 入力パスはラベル名の上位のディレクトリ
def load_handimage_bin(path):
 
    # ファイル一覧を取得
    files = glob.glob(os.path.join(path, '*/*.png'))
 
    # イメージとラベル領域を確保
    #images = np.ndarray((len(files), IMAGE_SIZE, IMAGE_SIZE,
    #                      COLOR_BYTE), dtype = np.uint8)
    images = np.ndarray((len(files), IMAGE_SIZE, IMAGE_SIZE)
                           , dtype = np.uint8)
 
    labels = np.ndarray(len(files), dtype=np.int)
 
    # イメージとラベルを読み込み
    for idx, file in enumerate(files):
        # イメージ読み込み
        image = io.imread(file)
        #image = cv2.GaussianBlur(image, (3,3), 0) # 必要に応じて、ぼかしでノイズ対策
        retval,image = cv2.threshold(image, threshhold, 255, cv2.THRESH_BINARY)
        images[idx] = image[:,:,0] | image[:,:,1] | image[:,:,2]
 
        # ディレクトリ名よりラベルを取得
        label = os.path.split(os.path.dirname(file))[-1]
        labels[idx] = int(label)
 
    # scikit-learn の他のデータセットの形式に合わせる
    flat_data = images.reshape((-1, IMAGE_SIZE * IMAGE_SIZE * COLOR_BYTE))
    images = flat_data.view()
    #return datasets.base.Bunch(data=images,
    return utils.Bunch(data=images,
                 target=labels.astype(np.int),
                 target_names=np.arange(CATEGORY_NUM),
                 images=images,
                 DESCR=None)
 
if __name__ == '__main__':
    import matplotlib.pyplot as plt

    d = load_handimage_bin("./data/m01")
    plt.figure(figsize=(8, 8))
    # 画像を 2 行 3 列に表示
    k = 0
    for i in range(6):
        for j in range(4):
            img = d.images[d.target==i][j]
            k += 1
            plt.subplot(6,4, k)
            plt.axis('off')
            plt.imshow(img.reshape(40,40), cmap="gray", interpolation='nearest')
            plt.title(i)
    plt.tight_layout()
    plt.show()

## load_handimage_bin.py

## WAVにかえるおー

In [ ]:
import os
import sys
import glob
import numpy as np
import librosa
from skimage import io
#from sklearn import datasets
from sklearn import utils
import cv2
import librosa.display

#COLOR_BYTE = 3
COLOR_BYTE = 1
CATEGORY_NUM = 6
threshhold = 80



#ラベル名(0～)を付けたディレクトリに分類されたイメージファイルを読み込む
#入力パスはラベル名の上位のディレクトリ
def load_wavimage_bin(path): 
#     # ファイル一覧を取得
#     files = glob.glob(os.path.join(path, '*/*.wav'))
#     # イメージとラベル領域を確保
#     images = np.ndarray((len(files), 128, 701)
#                            , dtype = np.uint8)
#     labels = np.ndarray(len(files), dtype=np.int) 
#     # イメージとラベルを読み込み
#     for idx, file in enumerate(files):
#         # イメージ読み込み
#         y,sr = librosa.load(path,sr=16000,offset=0.0,duration=7.0)
#         image = librosa.feature.melspectrogram(y=y,
#                                                 sr=sr,
#                                                 n_mels=128,
#                                                 n_fft=512,
#                                                 win_length=480,
#                                                 hop_length=160,)
#        # ディレクトリ名よりラベルを取得
#         label = os.path.split(os.path.dirname(file))[-1]
#         labels[idx] = int(label)
#      # scikit-learn の他のデータセットの形式に合わせる
#     flat_data = images.reshape((-1, 128 * 701 * COLOR_BYTE))
#     images = flat_data.view()
#     #return datasets.base.Bunch(data=images,
#     return utils.Bunch(data=images,
#                  target=labels.astype(np.int),
#                  target_names=np.arange(CATEGORY_NUM),
#                  images=images,
#                  DESCR=None)
    # ファイル一覧を取得
    files = glob.glob(os.path.join(path, '*/*.wav'))
    # イメージとラベル領域を確保
    images = np.ndarray((len(files), 128, 320), dtype = np.uint8)
    labels = np.ndarray(len(files), dtype=np.int)
    # イメージとラベルを読み込み
    for idx, file in enumerate(files):
        # イメージ読み込み
        y,sr = librosa.load(file,offset=0.0,duration=7.0)
        S = librosa.feature.melspectrogram(y=y,sr=sr,n_mels=128)
        image = librosa.amplitude_to_db(S, ref=np.max)

        # ディレクトリ名よりラベルを取得
        label = os.path.split(os.path.dirname(file))[-1]
        labels[idx] = int(label)
        
    flat_data = images.reshape((-1, 128 * 320 * COLOR_BYTE))
    images = flat_data.view()
    return utils.Bunch(data=images,
                 sr = sr,
                 target=labels.astype(np.int),
                 target_names=np.arange(CATEGORY_NUM),
                 images=images,
                 DESCR=None)
if __name__ == '__main__':
    import matplotlib.pyplot as plt

    d = load_wavimage_bin('./dataset/')
    plt.figure(figsize=(8, 8))
    # 画像を 2 行 3 列に表示
    k = 0
    for i in range(2):
        for j in range(4):
            img = d.images[d.target==i][j]
            k += 1
            plt.subplot(6,2, k)
            plt.axis('off')
            #plt.imshow(img.reshape(128,320), cmap="gray", interpolation='nearest')
            librosa.display.specshow(img, x_axis='time', y_axis='mel')
            plt.title(i)
    plt.tight_layout()
    plt.show()

In [2]:
import os
import sys
import glob
import numpy as np
import librosa
from skimage import io
#from sklearn import datasets
from sklearn import utils
import cv2

#COLOR_BYTE = 3
COLOR_BYTE = 1
CATEGORY_NUM = 6
threshhold = 80

In [3]:
path = './dataset/'

In [4]:
wav = './dataset/fujitou_normal/fujitou_normal_001.wav'

In [5]:
files = glob.glob(os.path.join(path, '*/*.wav'))

In [6]:
files

['./dataset/1/uemura_normal_071.wav',
 './dataset/1/uemura_normal_100.wav',
 './dataset/1/uemura_normal_041.wav',
 './dataset/1/uemura_normal_040.wav',
 './dataset/1/uemura_normal_057.wav',
 './dataset/1/uemura_normal_082.wav',
 './dataset/1/uemura_normal_010.wav',
 './dataset/1/uemura_normal_028.wav',
 './dataset/1/uemura_normal_075.wav',
 './dataset/1/uemura_normal_030.wav',
 './dataset/1/uemura_normal_006.wav',
 './dataset/1/uemura_normal_046.wav',
 './dataset/1/uemura_normal_025.wav',
 './dataset/1/uemura_normal_034.wav',
 './dataset/1/uemura_normal_073.wav',
 './dataset/1/uemura_normal_074.wav',
 './dataset/1/uemura_normal_087.wav',
 './dataset/1/uemura_normal_019.wav',
 './dataset/1/uemura_normal_042.wav',
 './dataset/1/uemura_normal_015.wav',
 './dataset/1/uemura_normal_007.wav',
 './dataset/1/uemura_normal_072.wav',
 './dataset/1/uemura_normal_011.wav',
 './dataset/1/uemura_normal_055.wav',
 './dataset/1/uemura_normal_094.wav',
 './dataset/1/uemura_normal_083.wav',
 './dataset/

In [7]:
images = np.ndarray((len(files), 128, 320), dtype = np.uint8)

In [8]:
images

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [9]:
labels = np.ndarray(len(files), dtype=np.int) 

In [10]:
labels

array([    140159037473536,     140159037473536,      94576613633856,
            94576613633856,                   0,                   0,
                        -1,                   0, 2318278683292336128,
                         0,                   9,     140157974279680,
            94576583861888,                  -1,                   0,
                        -1,     140157787893552, 3467820297745334272,
                        72,                   7,     140157974279680,
            94576583862084,                   0,                   1,
                         1,     140157787893552, 3184080309901590528,
                       144,                   3,     140157974279680,
            94576583862088,                   0,                   1,
                         1,                   0,                   0,
                       216,                   9,     140157974279680,
            94576583862136,                   0,                   4,
                    

In [11]:
# for idx, file in enumerate(files):
#     y,sr = librosa.load(file,sr=16000,offset=0.0,duration=7.0)

#     image = librosa.feature.melspectrogram(y=y,
#                                         sr=sr,
#                                         n_mels=128,
#                                         n_fft=512,
#                                         win_length=480,
#                                         hop_length=160,)

#     # ディレクトリ名よりラベルを取得
#     label = os.path.split(os.path.dirname(file))[-1]
#     labels[idx] = int(label)
for idx, file in enumerate(files):
    y,sr = librosa.load(file,offset=0.0,duration=7.0)
    S = librosa.feature.melspectrogram(y=y,sr=sr,n_mels=128)
    image = librosa.amplitude_to_db(S, ref=np.max)

    # ディレクトリ名よりラベルを取得
    label = os.path.split(os.path.dirname(file))[-1]
    labels[idx] = int(label)


In [17]:
import pandas as pd

#現在の最大表示列数の出力
pd.get_option("display.max_columns")

#最大表示列数の指定（ここでは50列を指定）
pd.set_option('display.max_columns', 50)

In [18]:
image

array([[-80., -80., -80., ..., -80., -80., -80.],
       [-80., -80., -80., ..., -80., -80., -80.],
       [-80., -80., -80., ..., -80., -80., -80.],
       ...,
       [-80., -80., -80., ..., -80., -80., -80.],
       [-80., -80., -80., ..., -80., -80., -80.],
       [-80., -80., -80., ..., -80., -80., -80.]], dtype=float32)

In [13]:
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [15]:
flat_data = images.reshape((-1, 128 * 320 * COLOR_BYTE))
images = flat_data.view()

In [22]:
print(images)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
labels

In [ ]:
y,sr = librosa.load(wav,sr=16000,offset=0.0,duration=7.0)

image = librosa.feature.melspectrogram(y=y,
                                        sr=sr,
                                        n_mels=128,
                                        n_fft=512,
                                        win_length=480,
                                        hop_length=160,)

# ディレクトリ名よりラベルを取得
label = os.path.split(os.path.dirname(file))[-1]
labels[idx] = int(label)

In [ ]:
# n_mels is number of Mel bands to generate
n_mels=128
# hop_length is number of samples between successive frames.
hop_length=2068
# n_fft is length of the FFT window
n_fft=2048
# Passing through arguments to the Mel filters
S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=n_mels, hop_length=hop_length, n_fft=n_fft)

log_S = librosa.power_to_db(log_S, np.max)
print(np.max)


plt.figure(figsize=(12, 4))
librosa.display.specshow(data=S, sr=sr, hop_length=hop_length, x_axis='time', y_axis='mel')
#librosa.display.specshow(data=log_S, sr=sr, hop_length=hop_length, x_axis='time', y_axis='mel')
plt.title('Mel spectrogram')
plt.tight_layout()

In [ ]:
# Load
y, sr = librosa.load(audio_path,sr=16000)


In [ ]:
import librosa
import glob
import numpy as np

In [ ]:
def extract_mel(wav, sr, n_mels=64): #Output -> (timeframe, mel_dim)
    audio, _ = librosa.load(wav, sr=sr)
    mel = librosa.feature.melspectrogram(y=audio, sr=sr, n_mels=n_mels).T
    return mel

In [ ]:
def data_list(path, sr, n_mels=64):
    wav_list = glob.glob(os.path.join(path, '*/*/*'))
    size = len(wav_list)
    data = np.ones((1, n_mels))
    count= 0
    for wavname in wav_list:
        component = extract_mel(wavname, sr=sr, n_mels=64)
        data = np.concatenate([data, component], axis=0)
        count += 1
        sys.stdout.write("\r%s" % "現在"+str(np.around((count/len(wav_list))*100 , 2))+"%完了")
        sys.stdout.flush()
    return data[1:], size

In [ ]:
from pydub import AudioSegment
